name = "Queers"
author = "Ryn"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "141326384720f448082e7a2be2f81a63b48b135cf211a9d9163298ba170e5d5a"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"
